name: Prettier

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install yarn
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Run Prettier
        run: |
          sudo yarn install
          sudo yarn prettier --check '**/*.rb'